#Launch Word (if not already created)
$Word = New-Object -ComObject Word.Application
$Word.Visible = $true

#Create a new blank document
$doc = $Word.Documents.Add()

#Write some content
#$text = $Word.Selection
$Word.Selection.TypeText("Hello from PowerShell. And Word Automation")
$Word.Selection.TypeParagraph()
$Word.Selection.TypeText("Created on: $(Get-Date -format 'yyyy-MM-dd HH:mm:ss')")
$Word.Selection.TypeParagraph()
$Word.Selection.TypeText("This document was generated by a PowerShell script.")

#Save path
$saveDoc = "c:"

#Save as DOCX (Format you want)
$wdFormatXMLDocument = 12
$doc.saveAs([ref] $saveDoc, [ref] $wdFormatXMLDocument)

#Close the document (True to save changes)
$doc.close($true)

#Quit Word
#Clean up
$Word.Quit()
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($Word) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($doc) | Out-Null
[System.Runtime.InteropServices.Marshal]::ReleaseComObject($Word) | Out-Null
[GC]::Collect()
[GC]::WaitForPendingFinalizers()

Write-Host "YOur Word Doc is completed" -ForegroundColor Yellow